/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppAvatar: typeof import('./components/common/AppAvatar.vue')['default']
    CommandPalette: typeof import('./components/common/CommandPalette.vue')['default']
    FocusMiniPlayer: typeof import('./components/focus/FocusMiniPlayer.vue')['default']
    FocusTimer: typeof import('./components/focus/FocusTimer.vue')['default']
    JournalEditor: typeof import('./components/journal/JournalEditor.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NModal: typeof import('naive-ui')['NModal']
    NRadio: typeof import('naive-ui')['NRadio']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    NTag: typeof import('naive-ui')['NTag']
    QuickAddTask: typeof import('./components/task/QuickAddTask.vue')['default']
    RoomCard: typeof import('./components/room/RoomCard.vue')['default']
    RoomChatBox: typeof import('./components/room/RoomChatBox.vue')['default']
    RoomMemberList: typeof import('./components/room/RoomMemberList.vue')['default']
    RoomMessageItem: typeof import('./components/room/RoomMessageItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StateEmpty: typeof import('./components/common/StateEmpty.vue')['default']
    StateError: typeof import('./components/common/StateError.vue')['default']
    StateLoading: typeof import('./components/common/StateLoading.vue')['default']
    TaskEditorDrawer: typeof import('./components/task/TaskEditorDrawer.vue')['default']
    TaskList: typeof import('./components/study/TaskList.vue')['default']
    TaskRow: typeof import('./components/task/TaskRow.vue')['default']
    ThemeSwitcher: typeof import('./components/common/ThemeSwitcher.vue')['default']
  }
}
