/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FocusTimer: typeof import('./components/focus/FocusTimer.vue')['default']
    JournalEditor: typeof import('./components/journal/JournalEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TaskList: typeof import('./components/study/TaskList.vue')['default']
  }
}
